[project]
name = "learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.8.0",
    "requests>=2.32.5",
    "pygame>=2.6.0",
]
